---
title: Benchmark iterations
jupyter:
  jupytext:
    formats: 'ipynb,qmd:quarto'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: R 4.4.1
    language: R
    name: ir441
---

# Setup

```{r}
# Working directory should be the root directory of repository.
# setwd("./")
renv::load()
source("./results/utils.R")

suppressPackageStartupMessages({
  # devtools::load_all("~/gits/ClemensKohl/CAdir/")
  library(CAdir)
  library(APL)

  library(SingleCellExperiment)
  library(scater)
  library(scuttle)
  library(scran)

  library(tidyr)
  library(dplyr)

  library(ggplot2)
  library(patchwork)
})

options(repr.plot.width = 20, repr.plot.height = 15)
set.seed(2358)
dir <- "./results/"
imgdir <- file.path(dir, "img/suppl_mat/iter_bench/")
resdir <- file.path(dir, "out/suppl_mat/iter_bench/")
dir.create(imgdir, recursive = TRUE)
dir.create(resdir, recursive = TRUE)
```

```{r}
data_dir <- file.path(
  "./data/real/preprocessed/benchmarking/"
)
data_files <- list.files(path = data_dir, pattern = "*.rds", full.names = TRUE)
data_files <- data_files[-grep("tabula_muris_sub", data_files)]
```

```{r}
zeisel_dir <- file.path(
  "./data/sim/preprocessed/zeisel/"
)
zeisel_files <- list.files(
  path = zeisel_dir,
  pattern = "*.rds",
  full.names = TRUE
)

pbmc3k_dir <- file.path(
  "./data/sim/preprocessed/pbmc3k/"
)
pbmc3k_files <- list.files(
  path = pbmc3k_dir,
  pattern = "*.rds",
  full.names = TRUE
)

sim_files <- c(zeisel_files, pbmc3k_files)
```

# Get max benchmarking results
## real
```{r}
date <- "20250528_cpu"
evldir <- file.path("./results/benchmarking/results/real/", date, "eval")
```

```{r}
### Load the results of real data sets
files <- list.files(evldir, "*.rds", full.names = TRUE)

df_paras <- data.frame()
for (file in files) {
  data <- readRDS(file)
  df_paras <- bind_rows(df_paras, data)
}

df_paras$dataset <- gsub("_filtered", "", df_paras$dataset)
```

```{r}
df_real <- df_paras %>%
  filter(algorithm == "CAdir_auto") %>%
  group_by(algorithm, dataset) %>%
  mutate(max_NMI = max(NMI, na.rm = TRUE)) %>%
  mutate(max_ARI = max(ARI, na.rm = TRUE)) %>%
  filter(ARI == max_ARI) %>%
  distinct(dataset, algorithm, max_ARI, .keep_all = TRUE) %>%
  ungroup()

df_real$max_NMI[is.infinite(df_real$max_NMI)] <- NA
df_real$max_ARI[is.infinite(df_real$max_ARI)] <- NA
```

## simulated
```{r}

date <- "20250528"
base_dir <- file.path("./results/benchmarking/results/simulated", date)
indir <- file.path(base_dir, "eval")
```

```{r}
zeisel_eval <- readRDS(
  file.path(
    indir,
    paste0(date, "_zeisel_collated.rds")
  )
)

dfz <- zeisel_eval %>%
  mutate(dataset = "zeisel") %>%
  mutate(simulation = paste(dePROB, defacLOC, defacSCALE, sep = "_")) %>%
  mutate(
    simulation = factor(
      simulation,
      levels = c(
        "0.02_0.75_0.75",
        "0.06_0.75_0.75",
        "0.1_0.75_0.75",
        "0.02_1.5_1.5",
        "0.06_1.5_1.5",
        "0.1_1.5_1.5"
      )
    )
  )
```

```{r}
pbmc_eval <- readRDS(
  file.path(
    indir,
    paste0(date, "_pbmc3k_collated.rds")
  )
)

dfp <- pbmc_eval %>%
  mutate(dataset = "pbmc3k") %>%
  mutate(simulation = paste(dePROB, defacLOC, defacSCALE, sep = "_")) %>%
  mutate(
    simulation = factor(
      simulation,
      levels = c(
        "0.02_0.75_0.75",
        "0.06_0.75_0.75",
        "0.1_0.75_0.75",
        "0.02_1.5_1.5",
        "0.06_1.5_1.5",
        "0.1_1.5_1.5"
      )
    )
  )
```

```{r}
df_all <- rbind(dfz, dfp)
df_sim <- df_all %>%
  filter(algorithm == "CAdir_auto") %>%
  mutate(sim = paste0(dataset, "_", simulation)) %>%
  group_by(simulation, algorithm, dataset) %>%
  mutate(max_ARI = max(ARI, na.rm = TRUE)) %>%
  mutate(max_NMI = max(NMI, na.rm = TRUE)) %>%
  filter(ARI == max_ARI) %>%
  distinct(
    dataset,
    simulation,
    algorithm,
    .keep_all = TRUE
  ) %>%
  ungroup()

df_sim$max_ARI[is.infinite(df_sim$max_ARI)] <- 0
df_sim$max_NMI[is.infinite(df_sim$max_NMI)] <- 0
```

# Benchmark iterations real
```{r}
iters <- seq.int(1, 50, by = 1)
# iters <- seq.int(0, 10, by = 5)

res_list_real <- vector(mode = "list", length = length(data_files))
options(rlib_message_verbosity = "quiet")
for (i in seq_len(length(data_files))) {
  iter_vec <- vector(mode = "numeric", length = length(iters))
  ari_vec <- vector(mode = "numeric", length = length(iters))

  f <- data_files[i]
  fnm <- gsub("_filtered.rds", "", basename(f))
  fnm <- gsub(".rds", "", fnm)
  cat("\n", fnm)
  sce <- readRDS(f)

  dft <- df_real %>% filter(dataset == fnm)

  if (dft$angle == 0) {
    cut_ang <- NULL
  } else {
    cut_ang <- dft$angle
  }

  set.seed(1234)
  sce_var <- scran::modelGeneVar(sce)
  sce_top <- scran::getTopHVGs(sce_var, n = dft$ntop, var.threshold = NULL)
  sce <- sce[sce_top, ]
  cnts <- as.matrix(logcounts(sce))

  ca <- cacomp(
    obj = cnts,
    princ_coords = 3,
    dims = dft$dims, #20
    top = nrow(cnts),
    residuals = "pearson",
    clip = TRUE
  )

  # Ensure that all iterations are initilized the same
  center_ids <- kmeanspp_init(points = ca@prin_coords_cols, k = dft$kdir)
  lines <- ca@prin_coords_cols[center_ids, ]

  for (j in seq_along(iters)) {
    n <- iters[j]
    cat("\n\titer:", n)
    set.seed(2358)
    cadir <- dirclust_splitmerge(
      caobj = ca,
      k = dft$kdir,
      cutoff = cut_ang,
      apl_quant = dft$apl_quant,
      reps = n,
      convergence_thr = FALSE,
      keep_log = FALSE,
      lines = lines
    )

    ari <- aricode::clustComp(cadir@cell_clusters, sce$truth)$ARI
    rm(cadir)
    ari_vec[j] <- ari
    iter_vec[j] <- n
  }

  res_list_real[[i]] <- data.frame(
    dataset = fnm,
    n_iters = iter_vec,
    ARI = ari_vec
  )
}
saveRDS(res_list_real, file = file.path(resdir, "real_res_list.rds"))
```

# Benchmark iterations sim

```{r}
iters <- seq.int(1, 50, by = 1)
# iters <- seq.int(0, 10, by = 5)
# iters[1] <- 1

res_list_sim <- vector(
  mode = "list",
  length = length(sim_files)
)
options(rlib_message_verbosity = "quiet")
for (i in seq_len(length(sim_files))) {
  iter_vec <- vector(mode = "numeric", length = length(iters))
  ari_vec <- vector(mode = "numeric", length = length(iters))

  f <- sim_files[i]
  fnm <- gsub("_filtered.rds", "", basename(f))
  fnm <- gsub("dePROB-", "", fnm)
  fnm <- gsub("defacLOC-", "", fnm)
  fnm <- gsub("defacSCALE-", "", fnm)
  fnm <- gsub(".rds", "", fnm)
  ds <- stringr::str_split(f, "/")[[1]][5]
  fnm <- paste0(ds, "_", fnm)
  cat("\n", fnm)
  sce <- readRDS(f)

  dft <- df_sim %>%
    mutate(dataset_gsub = gsub("\\.", "_", sim)) %>%
    filter(dataset_gsub == fnm)

  if (dft$angle == 0) {
    cut_ang <- NULL
  } else {
    cut_ang <- dft$angle
  }

  set.seed(1234)
  sce_var <- scran::modelGeneVar(sce)
  sce_top <- scran::getTopHVGs(sce_var, n = dft$ntop, var.threshold = NULL)
  sce <- sce[sce_top, ]
  cnts <- as.matrix(logcounts(sce))

  ca <- cacomp(
    obj = cnts,
    princ_coords = 3,
    dims = dft$dims, #20
    top = nrow(cnts),
    residuals = "pearson",
    clip = TRUE
  )

  # Ensure that all iterations are initilized the same
  center_ids <- kmeanspp_init(points = ca@prin_coords_cols, k = dft$kdir)
  lines <- ca@prin_coords_cols[center_ids, ]

  for (j in seq_along(iters)) {
    n <- iters[j]
    cat("\n\titer:", n)
    set.seed(2358)
    cadir <- dirclust_splitmerge(
      caobj = ca,
      k = dft$kdir,
      cutoff = cut_ang,
      apl_quant = dft$apl_quant,
      reps = n,
      convergence_thr = FALSE,
      keep_log = FALSE,
      lines = lines
    )

    ari <- aricode::clustComp(cadir@cell_clusters, sce$Group)$ARI
    rm(cadir)
    ari_vec[j] <- ari
    iter_vec[j] <- n
  }

  res_list_sim[[i]] <- data.frame(
    dataset = fnm,
    n_iters = iter_vec,
    ARI = ari_vec
  )
}
saveRDS(res_list_sim, file = file.path(resdir, "sim_res_list.rds"))
```

# Plot panels
```{r}

res_list_sim <- readRDS(file.path(resdir, "sim_res_list.rds"))
res_list_real <- readRDS(file.path(resdir, "real_res_list.rds"))
```

```{r}
dfr <- do.call(rbind, res_list_real)
dfr$dataset[dfr$dataset == "FreytagGold"] <- "Freytag Gold"
dfr$dataset[dfr$dataset == "PBMC_10X"] <- "PBMC10x"
dfr$dataset[dfr$dataset == "Tirosh_nonmaglignant"] <- "Tirosh"
dfr$dataset[dfr$dataset == "ZeiselBrain"] <- "Zeisel"
dfr$dataset[dfr$dataset == "BaronPancreas"] <- "Baron Pancreas"
dfr$dataset[dfr$dataset == "dmel_E14-16h"] <- "Dmel Spatial"
dfr$dataset[dfr$dataset == "tabula_sapiens_tissue"] <- "Tabula Sapiens"
dfr$dataset[dfr$dataset == "brain_organoids"] <- "Brain Organoids"
```

```{r}
dfs <- do.call(rbind, res_list_sim)
dfs$base <- sapply(dfs$dataset, function(x) stringr::str_split(x, "_")[[1]][1])
dfs$params <- gsub("zeisel_|pbmc3k_", "", dfs$dataset)
```

```{r}
# TODO: make panels for results

pr <- ggplot(
  dfr,
  aes(x = n_iters, y = ARI, color = dataset, group = dataset)
) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 1) +
  CAdir::scale_color_mpimg(name = "mpi_extend") +
  labs(
    title = "Nr. iterations vs. ARI - real data",
    x = "nr. iterations",
    y = "ARI",
    color = "Dataset"
  ) +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 11),
    plot.title = element_text(size = 12),
    legend.position = "bottom"
  )

ps <- ggplot(
  dfs,
  aes(x = n_iters, y = ARI, color = params, linetype = base, group = dataset)
) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 1) +
  CAdir::scale_color_mpimg(name = "mpi_extend") +
  labs(
    title = "Nr. iterations vs. ARI - sim. data",
    x = "nr. iterations",
    y = "ARI",
    color = "Dataset"
  ) +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 11),
    plot.title = element_text(size = 12),
    legend.position = "bottom"
  )
```

```{r}

panel <- pr +
  ps +
  # guides(fill = guide_legend(nrow = 3, byrow = TRUE)) +
  # plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.tag = element_text(size = 18, face = "bold"),
    legend.position = "bottom",
    legend.box = "vertical",
    legend.margin = margin()
  )

ggsave(
  filename = file.path(imgdir, "n_iter_splitmerge_panel.pdf"),
  plot = panel,
  width = 4000,
  height = 2000,
  units = "px"
)

ggsave(
  filename = file.path(imgdir, "n_iter_splitmerge_panel.png"),
  plot = panel,
  width = 4000,
  height = 2000,
  units = "px"
)

ggsave(
  filename = file.path(imgdir, "n_iter_splitmerge_panel.tiff"),
  plot = panel,
  width = 4000,
  height = 2000,
  units = "px"
)
```


# session info
```{r}
sessionInfo()
```

