---
title: n rnd iterations
jupyter:
  jupytext:
    formats: 'ipynb,qmd:quarto'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: R 4.4.1
    language: R
    name: ir441
---

# Setup

```{r}
# Working directory should be the root directory of repository.
# setwd("./")
renv::load()
source("./results/utils.R")

suppressPackageStartupMessages({
  devtools::load_all("~/gits/ClemensKohl/CAdir/")
  # library(CAdir)
  library(APL)

  library(SingleCellExperiment)
  library(scater)
  library(scuttle)
  library(scran)

  library(tidyr)
  library(dplyr)

  library(ggplot2)
  library(patchwork)
})

options(repr.plot.width = 20, repr.plot.height = 15)
set.seed(2358)
dir <- "./results/"
imgdir <- file.path(dir, "img/review2/n_rnd_iters/")
resdir <- file.path(dir, "out/review2/n_rnd_iters/")
dir.create(imgdir, recursive = TRUE)
dir.create(resdir, recursive = TRUE)
```

```{r}
data_dir <- file.path(
  "./data/real/preprocessed/benchmarking/"
)
data_files <- list.files(path = data_dir, pattern = "*.rds", full.names = TRUE)
data_files <- data_files[-grep("tabula_muris_sub", data_files)]
```

# get_apl_cutoff function
```{r}
#NOTE: Normally CAdir sets apl_cutoff_reps to 100 if <100.
# This function is adapted to allow for reps <100.
get_apl_cutoff_mod <- function(
  caobj,
  method = "random",
  group = caobj@group,
  counts = NULL,
  quant = 0.99,
  apl_cutoff_reps = 100,
  axis = "cols"
) {
  if (method == "random") {
    if (is.null(apl_cutoff_reps)) {
      apl_cutoff_reps <- 100
    } else if (apl_cutoff_reps < 100) {
      # NOTE: commented out to allow for less reps
      # rlang::warn("Number of repetitions should be set >=100.")
      # apl_cutoff_reps <- 100
    }

    apl_cotan <- random_direction_cutoff(
      caobj = caobj,
      dims = caobj@dims,
      apl_cutoff_reps = apl_cutoff_reps,
      axis = axis
    )
  } else if (method == "permutation") {
    if (is.null(apl_cutoff_reps)) {
      apl_cutoff_reps <- 5
    } else if (apl_cutoff_reps > 10) {
      rlang::inform("Large number of repetitions might take a long time.")
    }

    apl_cotan <- permutation_cutoff(
      caobj = caobj,
      counts = counts,
      group = group,
      dims = caobj@dims,
      apl_cutoff_reps = apl_cutoff_reps,
      python = TRUE,
      axis = axis
    )
  }

  cutoff_cotan <- stats::quantile(apl_cotan, quant)

  # tan = 1/cotan
  # angle alpha is in radian.
  alpha <- atan(1 / cutoff_cotan)

  return(alpha)
}
```



# Get max benchmarking results
```{r}
date <- "20250528_cpu"
evldir <- file.path("./results/benchmarking/results/real/", date, "eval")
```

```{r}
### Load the results of real data sets
files <- list.files(evldir, "*.rds", full.names = TRUE)

df_paras <- data.frame()
for (file in files) {
  data <- readRDS(file)
  df_paras <- bind_rows(df_paras, data)
}

df_paras$dataset <- gsub("_filtered", "", df_paras$dataset)
```



```{r}
df_real <- df_paras %>%
  filter(algorithm == "CAdir_auto") %>%
  group_by(algorithm, dataset) %>%
  mutate(max_NMI = max(NMI, na.rm = TRUE)) %>%
  mutate(max_ARI = max(ARI, na.rm = TRUE)) %>%
  filter(ARI == max_ARI) %>%
  distinct(dataset, algorithm, max_ARI, .keep_all = TRUE) %>%
  ungroup()

df_real$max_NMI[is.infinite(df_real$max_NMI)] <- NA
df_real$max_ARI[is.infinite(df_real$max_ARI)] <- NA
```

# Benchmark number of random directions
```{r}
iters <- seq.int(0, 1000, by = 10)
# iters <- seq.int(0, 30, by = 10)
iters[1] <- 1

files_list <- vector(mode = "list", length = length(data_files))

options(rlib_message_verbosity = "quiet")
for (i in seq_len(length(data_files))) {
  rnd_vec <- vector(mode = "numeric", length = length(iters))
  rnd_ari_vec <- vector(mode = "numeric", length = length(iters))
  n_it <- vector(mode = "character", length = length(iters))
  f <- data_files[i]
  fnm <- gsub("_filtered.rds", "", basename(f))
  fnm <- gsub(".rds", "", fnm)
  cat("\n", fnm)

  sce <- readRDS(f)

  if (fnm == "tabula_muris_sub") {
    sce$truth <- sce$cell_ontology_class
  }

  dft <- df_real %>% filter(dataset == fnm)
  if (dft$angle == 0) {
    cut_ang <- NULL
  } else {
    cut_ang <- dft$angle
  }
  set.seed(1234)
  sce_var <- scran::modelGeneVar(sce)
  sce_top <- scran::getTopHVGs(sce_var, n = dft$ntop, var.threshold = NULL)
  sce <- sce[sce_top, ]
  cnts <- as.matrix(logcounts(sce))

  ca <- cacomp(
    obj = cnts,
    princ_coords = 3,
    dims = dft$dims, #20
    top = nrow(cnts),
    residuals = "pearson",
    clip = TRUE
  )

  cadir <- dirclust_splitmerge(
    caobj = ca,
    k = dft$kdir,
    cutoff = cut_ang,
    method = "random",
    apl_quant = dft$apl_quant,
    reps = 15,
    keep_log = FALSE
  )

  # Ensure that all iterations are initilized the same
  center_ids <- kmeanspp_init(points = ca@prin_coords_cols, k = dft$kdir)
  lines <- ca@prin_coords_cols[center_ids, ]

  for (j in seq_along(iters)) {
    n <- iters[j]
    cat("\n\titer", n)

    rnd_cutoff <- get_apl_cutoff_mod(
      caobj = ca,
      method = "random",
      group = which(cadir@cell_clusters == "cluster_1"),
      counts = NULL,
      quant = 0.99,
      apl_cutoff_reps = n,
      axis = "cols"
    )

    rnd_ang <- CAdir:::rad2deg(rnd_cutoff)

    cadir_rnd <- dirclust_splitmerge(
      caobj = ca,
      k = dft$kdir,
      cutoff = rnd_ang,
      apl_quant = dft$apl_quant,
      reps = 15,
      keep_log = FALSE,
      lines = lines
    )

    sce$cadir_rnd <- cadir_rnd@cell_clusters
    rm(cadir_rnd)
    ari_rnd <- aricode::clustComp(sce$cadir_rnd, sce$truth)$ARI

    rnd_vec[j] <- rnd_ang
    names(rnd_vec)[j] <- fnm

    rnd_ari_vec[j] <- ari_rnd
    names(rnd_ari_vec)[j] <- fnm

    n_it[j] <- n
  }

  files_list[[i]] <- data.frame(
    n_iters = n_it,
    dataset = fnm,
    cutoff_angle = rnd_vec,
    ARI = rnd_ari_vec
  )
}
saveRDS(files_list, file = file.path(resdir, "files_list.rds"))
```

# Plot panel

```{r}
files_list <- readRDS(file.path(resdir, "files_list.rds"))
```


```{r}
df <- do.call(rbind, files_list)
df$n_iters <- as.integer(df$n_iters)
df$dataset[df$dataset == "FreytagGold"] <- "Freytag Gold"
df$dataset[df$dataset == "PBMC_10X"] <- "PBMC10x"
df$dataset[df$dataset == "Tirosh_nonmaglignant"] <- "Tirosh"
df$dataset[df$dataset == "ZeiselBrain"] <- "Zeisel"
df$dataset[df$dataset == "BaronPancreas"] <- "Baron Pancreas"
df$dataset[df$dataset == "dmel_E14-16h"] <- "Dmel Spatial"
df$dataset[df$dataset == "tabula_sapiens_tissue"] <- "Tabula Sapiens"
df$dataset[df$dataset == "brain_organoids"] <- "Brain Organoids"
```

```{r}
# df <- df[!is.na(df$dataset) & df$dataset != "", ]

p_ari <- ggplot(
  df,
  aes(x = n_iters, y = ARI, color = dataset, group = dataset)
) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 1.5) +
  CAdir::scale_color_mpimg(name = "mpi_extend") +
  labs(
    title = "Effect of number of random directions on ARI",
    x = "nr. random directions",
    y = "ARI",
    color = "Dataset"
  ) +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 11),
    plot.title = element_text(size = 12),
    legend.position = "bottom"
  )

p_ang <- ggplot(
  df,
  aes(x = n_iters, y = cutoff_angle, color = dataset, group = dataset)
) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 1.5) +
  CAdir::scale_color_mpimg(name = "mpi_extend") +
  labs(
    title = "Effect of number of random directions on cutoff angle",
    x = "nr. random directions",
    y = "angle [degrees]",
    color = "Dataset"
  ) +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 11),
    plot.title = element_text(size = 12),
    legend.position = "bottom"
  )
```

```{r}
panel <- p_ang +
  p_ari +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.tag = element_text(size = 18, face = "bold"),
    legend.position = "bottom",
    legend.box = "vertical",
    legend.margin = margin()
  )

ggsave(
  filename = file.path(imgdir, "n_rnd_iters_panel.pdf"),
  plot = panel,
  width = 4000,
  height = 2000,
  units = "px"
)

ggsave(
  filename = file.path(imgdir, "n_rnd_iters_panel.png"),
  plot = panel,
  width = 4000,
  height = 2000,
  units = "px"
)

ggsave(
  filename = file.path(imgdir, "n_rnd_iters_panel.tiff"),
  plot = panel,
  width = 4000,
  height = 2000,
  units = "px"
)
```

```{r}
sessionInfo()
```

