---
title: APL & violin plots
jupyter:
  jupytext:
    formats: 'ipynb,qmd:quarto'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: R 4.4.1
    language: R
    name: ir441
---

# Setup
```{r}
renv::load()
source("./results/utils.R")
suppressPackageStartupMessages({
  # devtools::load_all("~/gits/ClemensKohl/CAdir/")
  library(CAdir)
  library(APL)

  library(SingleCellExperiment)
  library(scater)
  library(scuttle)
  library(scran)

  library(tidyr)
  library(dplyr)

  library(ggplot2)
  library(ggbeeswarm)
  library(patchwork)
  library(svglite)
})

options(repr.plot.width = 20, repr.plot.height = 15)
set.seed(2358)

dir <- "./results/"
imgdir <- file.path(dir, "img/suppl_mat/apl_violins/")
resdir <- file.path(dir, "out/suppl_mat/apl_violins/")
dir.create(imgdir, recursive = TRUE)
dir.create(resdir, recursive = TRUE)
```

## Load data

```{r}
data_dir <- "./data/real/discussed/"

marker_genes <- readr::read_csv(file.path(
  data_dir,
  "tabula_muris_marker_genes.csv"
))
sce <- readRDS(file.path(
  data_dir,
  "preprocessed/tabula_muris_preprocessed_filtered.rds"
))

genevars <- modelGeneVar(sce, assay.type = "logcounts")
chosen <- getTopHVGs(genevars, n = 6000, var.threshold = NULL)

# add marker_genes
expr_markers <- marker_genes[marker_genes$gene %in% rownames(sce), ]
chosen <- c(chosen, expr_markers$gene)
chosen <- unique(chosen)
sce_sub <- sce[chosen, ]

ca <- cacomp(
  obj = logcounts(sce_sub),
  princ_coords = 3,
  dims = 30,
  top = nrow(sce_sub),
  residuals = "pearson",
  python = TRUE
)

cell_types <- sce$cell_ontology_class
cat("Number of cell types:", length(unique(cell_types)), "\n")
```

# CAdir

```{r}
set.seed(2358)
cak <- dirclust_splitmerge(
  caobj = ca,
  k = 8,
  cutoff = 55,
  method = "random",
  apl_quant = 0.99,
  counts = NULL,
  min_cells = 20,
  reps = NULL,
  make_plots = TRUE,
  qcutoff = 0.8,
  convergence_thr = 0.001
)
```

Annotate biclustering:

```{r}
cak <- annotate_biclusters(
  obj = cak,
  caobj = ca,
  universe = rownames(sce_sub),
  org = "mm",
  method = "goa",
  cost = "logpval",
  filter_literature = FALSE
)

sce_sub$cadir <- cak@cell_clusters
cak <- rank_genes(cak, caobj = ca)
cak
```

# APL B cells

```{r}
cls <- "B_cell"
selected_bc_genes <- c("Bmf", "Cd74", "Ly6d", "Cd79a", "Cd19")
group <- which(cak@cell_clusters == cls)

model <- apl_model(
  coords = methods::slot(ca, name = "std_coords_cols"),
  direction = cak@directions[cls, ] / ca@D,
  group = group
)
gcoords <- model(ca@prin_coords_rows)
gcoords <- gcoords[rownames(gcoords) %in% selected_bc_genes, ]
gcoords <- as_tibble(gcoords, rownames = "gene")
gcoords$info <- "gene"

p_bt_std <- cluster_apl(
  caobj = ca,
  cadir = cak,
  cluster = cls,
  direction = cak@directions[cls, ],
  group = group,
  highlight_cluster = TRUE,
  show_genes = TRUE,
  label_genes = FALSE,
  show_lines = FALSE,
  size_factor = 1,
  point_size = 3,
  ntop = 5
) +
  geom_point(
    data = gcoords,
    aes(x = x, y = y),
    color = "#c4421a",
    size = 4,
    shape = 8,
    stroke = 1.5,
    inherit.aes = FALSE
  ) +
  ggrepel::geom_text_repel(
    data = gcoords,
    aes(x = x, y = y, label = gene, info = gene),
    size = 5,
    max.overlaps = Inf,
    colour = "#c4421a",
    bg.color = "black",
    bg.r = .05 # NOTE: remove if bg wrong size.
  ) +
  ggtitle("B cells") +
  theme_bw(
    base_size = 18
  ) +
  theme(
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black"),
    plot.title = element_text(size = 22, color = "black", face = "bold")
  )


# NOTE: Uncomment to plot
# p_bt_std

ggsave(
  plot = p_bt_std,
  file = file.path(imgdir, "B_cell_cluster_std_coords.pdf"),
  device = cairo_pdf,
  width = 2000,
  height = 1600,
  units = "px"
)
ggsave(
  plot = p_bt_std,
  file = file.path(imgdir, "B_cell_cluster_std_coords.png"),
  width = 2000,
  height = 1600,
  units = "px"
)

# p_bt_std_int <- cluster_apl(
#   caobj = ca,
#   cadir = cak,
#   cluster = cls,
#   direction = cak@directions[cls, ],
#   group = which(cak@cell_clusters == cls),
#   highlight_cluster = TRUE,
#   show_genes = TRUE,
#   show_cells = TRUE,
#   label_genes = TRUE,
#   show_lines = FALSE,
#   size_factor = 0.5,
#   ntop = 5,
#   interactive = TRUE
# )
#
# htmlwidgets::saveWidget(
#   p_bt_std_int,
#   file = file.path(imgdir, "interactive_bcells.html")
# )
```

# APL endothelial cells
```{r}
cls <- "Endothelial_cell"
selected_e_genes <- c("Dlg2", "Itpkb", "Kitl", "Pecam1", "Cdh5") #"Itga1",
group <- which(cak@cell_clusters == cls)

model <- apl_model(
  coords = methods::slot(ca, name = "std_coords_cols"),
  direction = cak@directions[cls, ] / ca@D,
  group = group
)
gcoords <- model(ca@prin_coords_rows)
gcoords <- gcoords[rownames(gcoords) %in% selected_e_genes, ]
gcoords <- as_tibble(gcoords, rownames = "gene")
gcoords$info <- "gene"

p_e_std <- cluster_apl(
  caobj = ca,
  cadir = cak,
  cluster = cls,
  direction = cak@directions[cls, ],
  group = group,
  highlight_cluster = TRUE,
  show_genes = TRUE,
  label_genes = FALSE,
  show_lines = FALSE,
  point_size = 3,
  size_factor = 1,
  ntop = 5
) +
  geom_point(
    data = gcoords,
    aes(x = x, y = y),
    color = "#c4421a",
    size = 4,
    shape = 8,
    stroke = 1.5,
    inherit.aes = FALSE
  ) +
  ggrepel::geom_text_repel(
    data = gcoords,
    aes(x = x, y = y, label = gene, info = gene),
    size = 5,
    max.overlaps = Inf,
    colour = "#c4421a",
    bg.color = "black",
    bg.r = .05 # NOTE: remove if bg wrong size.
  ) +
  ggtitle("Endothelial cells") +
  theme_bw(
    base_size = 18
  ) +
  theme(
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black"),
    plot.title = element_text(size = 22, color = "black", face = "bold")
  )

# NOTE: Uncomment to plot
# p_e_std

ggsave(
  plot = p_e_std,
  file = file.path(imgdir, "endothelial_cluster_std_coords.pdf"),
  device = cairo_pdf,
  width = 2000,
  height = 1600,
  units = "px"
)
ggsave(
  plot = p_e_std,
  file = file.path(imgdir, "endothelial_cluster_std_coords.png"),
  width = 2000,
  height = 1600,
  units = "px"
)

# p_e_std_int <- cluster_apl(
#   caobj = ca,
#   cadir = cak,
#   cluster = cls,
#   direction = cak@directions[cls, ],
#   group = which(cak@cell_clusters == cls),
#   highlight_cluster = TRUE,
#   show_genes = TRUE,
#   show_cells = TRUE,
#   label_genes = TRUE,
#   show_lines = FALSE,
#   size_factor = 0.5,
#   ntop = 5,
#   interactive = TRUE
# )
#
# htmlwidgets::saveWidget(
#   p_e_std_int,
#   file = file.path(imgdir, "interactive_endo.html")
# )
```
# APL + violin panel

Select genes spread along the association-strength (x) axis of the B cell APL,
then draw a violin plot per gene and connect each violin back to its point.


```{r}
## Build one violin plot per gene
expr_mat <- as.matrix(logcounts(sce_sub))
gene_norm <- CAdir:::row_norm(ca@prin_coords_rows)

violin_b_list <- lapply(selected_bc_genes, function(g) {
  df <- data.frame(
    expr = expr_mat[g, ],
    group = as.character(cak@cell_clusters)
  )
  stheta <- cak@gene_ranks$B_cell$Score[cak@gene_ranks$B_cell$Rowname == g]
  gnorm <- gene_norm[g]
  ggplot(df, aes(x = group, y = expr, fill = group)) +
    geom_violin(scale = "width", trim = TRUE, alpha = 0.1) +
    geom_quasirandom(
      aes(color = group),
      size = 0.8,
      alpha = 0.65,
      bandwidth = 0.3
    ) +
    scale_fill_mpimg(name = "mpimg") +
    scale_color_mpimg(name = "mpimg") +
    labs(
      y = "log-counts",
      title = paste0(
        g,
        ", ",
        "S\u03b8: ",
        round(stheta, 2),
        ", norm: ",
        round(gnorm, 2)
      )
    ) +
    theme_bw(base_size = 12) +
    theme(
      legend.position = "none",
      axis.title.x = element_blank(),
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        size = 10,
        color = "black"
      ),
      axis.text.y = element_text(size = 10, color = "black"),
      plot.title = element_text(size = 11, hjust = 0.5, face = "italic")
    )
})

violin_b_row <- wrap_plots(violin_b_list, nrow = 1)

beeswarm_b_list <- lapply(selected_bc_genes, function(g) {
  df <- data.frame(
    expr = expr_mat[g, ],
    group = as.character(cak@cell_clusters)
  )
  ggplot(df, aes(x = group, y = expr, color = group)) +
    geom_quasirandom(size = 0.7, alpha = 0.55, bandwidth = 0.3) +
    scale_color_mpimg(name = "mpimg") +
    labs(y = "log-counts", title = g) +
    theme_bw(base_size = 12) +
    theme(
      legend.position = "none",
      axis.title.x = element_blank(),
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        size = 10,
        color = "black"
      ),
      axis.text.y = element_text(size = 10, color = "black"),
      plot.title = element_text(size = 11, hjust = 0.5, face = "italic")
    )
})

beeswarm_b_row <- wrap_plots(beeswarm_b_list, nrow = 1)
```

```{r}

violin_e_list <- lapply(selected_e_genes, function(g) {
  df <- data.frame(
    expr = expr_mat[g, ],
    group = as.character(cak@cell_clusters)
  )
  stheta <- cak@gene_ranks$Endothelial_cell$Score[
    cak@gene_ranks$Endothelial_cell$Rowname == g
  ]
  gnorm <- gene_norm[g]
  ggplot(df, aes(x = group, y = expr, fill = group)) +
    geom_violin(scale = "width", trim = TRUE, alpha = 0.1) +
    geom_quasirandom(
      aes(color = group),
      size = 0.8,
      alpha = 0.65,
      bandwidth = 0.3
    ) +
    scale_fill_mpimg(name = "mpimg") +
    scale_color_mpimg(name = "mpimg") +
    labs(
      y = "log-counts",
      title = paste0(
        g,
        ", ",
        "S\u03b8: ",
        round(stheta, 2),
        ", norm: ",
        round(gnorm, 2)
      )
    ) +
    theme_bw(base_size = 12) +
    theme(
      legend.position = "none",
      axis.title.x = element_blank(),
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        size = 10,
        color = "black"
      ),
      axis.text.y = element_text(size = 10, color = "black"),
      plot.title = element_text(size = 11, hjust = 0.5, face = "italic")
    )
})
violin_e_row <- wrap_plots(violin_e_list, nrow = 1)

beeswarm_e_list <- lapply(selected_e_genes, function(g) {
  df <- data.frame(
    expr = expr_mat[g, ],
    group = as.character(cak@cell_clusters)
  )
  ggplot(df, aes(x = group, y = expr, color = group)) +
    geom_quasirandom(size = 0.7, alpha = 0.55, bandwidth = 0.3) +
    scale_color_mpimg(name = "mpimg") +
    labs(y = "log-counts", title = g) +
    theme_bw(base_size = 12) +
    theme(
      legend.position = "none",
      axis.title.x = element_blank(),
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        size = 10,
        color = "black"
      ),
      axis.text.y = element_text(size = 10, color = "black"),
      plot.title = element_text(size = 11, hjust = 0.5, face = "italic")
    )
})
beeswarm_e_row <- wrap_plots(beeswarm_e_list, nrow = 1)
```


```{r}
apl_frac <- 2 / 3 # fraction of total height for APL
b_combined <- p_bt_std /
  violin_b_row +
  plot_layout(heights = c(apl_frac, 1 - apl_frac))

e_combined <- p_e_std /
  violin_e_row +
  plot_layout(heights = c(apl_frac, 1 - apl_frac))

b_beeswarm_combined <- p_bt_std /
  beeswarm_b_row +
  plot_layout(heights = c(apl_frac, 1 - apl_frac))

e_beeswarm_combined <- p_e_std /
  beeswarm_e_row +
  plot_layout(heights = c(apl_frac, 1 - apl_frac))
```

```{r}
## Render and save
ggsave(
  plot = b_combined,
  file = file.path(imgdir, "B_cell_apl_violins.png"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = e_combined,
  file = file.path(imgdir, "endothelial_apl_violins.png"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = b_beeswarm_combined,
  file = file.path(imgdir, "B_cell_apl_beeswarm.png"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = e_beeswarm_combined,
  file = file.path(imgdir, "endothelial_apl_beeswarm.png"),
  width = 5000,
  height = 3000,
  units = "px"
)
```

```{r}
## Render and save
ggsave(
  plot = b_combined,
  file = file.path(imgdir, "B_cell_apl_violins.pdf"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = e_combined,
  file = file.path(imgdir, "endothelial_apl_violins.pdf"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = b_beeswarm_combined,
  file = file.path(imgdir, "B_cell_apl_beeswarm.pdf"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = e_beeswarm_combined,
  file = file.path(imgdir, "endothelial_apl_beeswarm.pdf"),
  width = 5000,
  height = 3000,
  units = "px"
)
```

```{r}
## Render and save
ggsave(
  plot = b_combined,
  file = file.path(imgdir, "B_cell_apl_violins.svg"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = e_combined,
  file = file.path(imgdir, "endothelial_apl_violins.svg"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = b_beeswarm_combined,
  file = file.path(imgdir, "B_cell_apl_beeswarm.svg"),
  width = 5000,
  height = 3000,
  units = "px"
)

ggsave(
  plot = e_beeswarm_combined,
  file = file.path(imgdir, "endothelial_apl_beeswarm.svg"),
  width = 5000,
  height = 3000,
  units = "px"
)
```

# sessionInfo
```{r}
sessionInfo()
```

