---
title: Batch
jupyter:
  jupytext:
    formats: 'ipynb,qmd:quarto'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: R 4.4.1
    language: R
    name: ir441
---

# Setup

```{r}
# Working directory should be the root directory of repository.
# setwd("./")
renv::load()
source("./results/utils.R")

suppressPackageStartupMessages({
  library(CAdir)
  library(APL)

  library(SingleCellExperiment)
  library(scater)
  library(scuttle)
  library(scran)
  library(batchelor)

  library(dplyr)

  library(patchwork)
})

options(repr.plot.width = 20, repr.plot.height = 15)

dir <- "./results/"
imgdir <- file.path(dir, "img/batch/")
dir.create(imgdir, recursive = TRUE)

```


## Load data
<https://figshare.com/articles/dataset/Benchmarking_atlas-level_data_integration_in_single-cell_genomics_-_integration_task_datasets_Immune_and_pancreas_/12420968?file=24539828>
```{r}
data_dir <- "./data/real/raw/"

sce <- readRDS(file.path(data_dir, "human_pancreas_norm_complexBatch.rds"))


genevars <- modelGeneVar(sce, assay.type = "logcounts")
chosen <- getTopHVGs(genevars, n = 6000, var.threshold = NULL)
sce_sub <- sce[chosen, ]

# sce_sub <- fixedPCA(sce_sub, rank = 50, subset.row = chosen)
# sce_sub <- runUMAP(sce_sub, dimred = "PCA")
```



# CA 
```{r}
ca <- cacomp(
  obj = logcounts(sce_sub),
  princ_coords = 3,
  dims = 50,
  top = nrow(sce_sub),
  residuals = "pearson"
)

cell_types <- sce$celltype
cat("Number of cell types:", length(unique(cell_types)), "\n")
```

# CAdir

```{r}
set.seed(2358)
cabic <- dirclust_splitmerge(
  caobj = ca,
  k = 14,
  cutoff = 55,
  method = "random",
  apl_quant = 0.99,
  counts = NULL,
  min_cells = 20,
  reps = NULL,
  make_plots = TRUE,
  qcutoff = 0.8,
  convergence_thr = 0.001
)
```

Annotate biclustering:

```{r}
cabic <- annotate_biclustering(
  obj = cabic,
  universe = rownames(sce_sub),
  org = "hs"
)

sce_sub$cadir <- cabic@cell_clusters

cabic
```

```{r} 
```

```{r}
um1 <- plotUMAP(sce_sub, colour = "cadir")
um2 <- plotUMAP(sce_sub, colour = "celltype")
um3 <- plotUMAP(sce_sub, colour = "tech")

ari <- aricode::clustComp(sce_sub$cadir, sce_sub$celltype)
cat("ARI:", ari$ARI, "\n")

um <- (um2 | um3) /
  (um1 + ggtitle(paste0("ARI: ", round(ari$ARI, 2))))

um

ggsave(
  plot = um,
  filename = file.path(imgdir, "batch_umap.png"),
  width = 2400,
  height = 1600,
  units = "px"
)
```

# Cluster Association Plots

```{r}
pcl <- plot_clusters(
  cadir = cabic,
  caobj = ca,
  show_genes = TRUE,
  label_genes = TRUE,
  ntop = 5,
  title_prefix = "",
  axis = TRUE,
  text_size = 19,
  legend_pos = "right",
  return_list = TRUE,
  gsub_title = "_"
)
pcl <- wrap_plots(pcl, ncol = 3) +
  guide_area() +
  plot_layout(guides = "collect")

pcl

ggsave(
  plot = pcl,
  filename = file.path(imgdir, "cluster_apls.pdf"),
  device = cairo_pdf,
  width = 3400,
  height = 2000,
  units = "px"
)

ggsave(
  plot = pcl,
  filename = file.path(imgdir, "cluster_apls.png"),
  width = 3400,
  height = 2000,
  units = "px"
)
```

# Batch correction

```{r}
batch_corr <- quickCorrect(
  sce_sub,
  batch = sce_sub$tech,
  PARAM = FastMnnParam(BSPARAM = BiocSingular::RandomParam()),
  hvg.args = list(n = 5000)
)

sce_corr <- batch_corr$corrected
```

```{r}
stopifnot(identical(rownames(colData(sce_corr)), rownames(colData(sce_sub))))
sce_corr$celltype <- sce_sub$celltype

sce_corr <- runUMAP(sce_corr, dimred = "corrected")
um4 <- plotUMAP(sce_corr, colour = "batch")
um5 <- plotUMAP(sce_corr, colour = "celltype")
```

```{r}

reconstr <- as.matrix(assay(sce_corr, "reconstructed"))
reconstr <- reconstr + abs(min(reconstr))

ca_corr <- cacomp(
  obj = reconstr,
  princ_coords = 3,
  dims = 50,
  top = nrow(sce_corr),
  residuals = "pearson"
)

cell_types <- sce$celltype
cat("Number of cell types:", length(unique(cell_types)), "\n")
```

# CAdir

```{r}
set.seed(2358)
cabic_corr <- dirclust_splitmerge(
  caobj = ca_corr,
  k = 14,
  cutoff = 55,
  method = "random",
  apl_quant = 0.99,
  counts = NULL,
  min_cells = 20,
  reps = NULL,
  make_plots = TRUE,
  qcutoff = 0.8,
  convergence_thr = 0.001
)
```

```{r}
sce_corr$cadir <- cabic_corr@cell_clusters
ari <- aricode::clustComp(sce_corr$cadir, sce_corr$celltype)
cat("ARI:", ari$ARI, "\n")

```

```{r}
cabic_corr <- annotate_biclustering(
  obj = cabic_corr,
  universe = rownames(sce_corr),
  org = "hs"
)

sce_corr$cadir <- cabic_corr@cell_clusters
cabic
```

```{r}
um6 <- plotUMAP(sce_corr, colour = "cadir")

um <- (um4 | um5) /
  (um6 + ggtitle(paste0("ARI: ", round(ari$ARI, 2))))
um

ggsave(
  plot = um,
  filename = file.path(imgdir, "batch_corr_umap.png"),
  width = 2400,
  height = 1600,
  units = "px"
)

```

```{r}
sessionInfo()
```

