---
title: Marker Genes
jupyter:
  jupytext:
    formats: 'ipynb,qmd:quarto'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: R 4.4.1
    language: R
    name: ir441
---

# Setup

```{r}
# Working directory should be the root directory of repository.
# setwd("./")
renv::load()
source("./results/utils.R")

suppressPackageStartupMessages({
  library(CAdir)
  library(APL)

  library(SingleCellExperiment)
  library(scater)
  library(scuttle)
  library(scran)

  library(tidyr)

  library(ggplot2)
  library(patchwork)
})

options(repr.plot.width = 20, repr.plot.height = 15)
set.seed(2358)
dir <- "./results/"
imgdir <- file.path(dir, "img/review/random_vs_perm/")
resdir <- file.path(dir, "out/review/random_vs_perm/")
dir.create(imgdir, recursive = TRUE)
dir.create(resdir, recursive = TRUE)
```

```{r}
data_dir <- file.path(
  "./data/real/preprocessed/benchmarking/"
)
files <- list.files(path = data_dir, pattern = "*.rds", full.names = TRUE)
```

```{r}

rnd_vec <- vector(mode = "numeric", length = length(files))
perm_vec <- vector(mode = "numeric", length = length(files))

rnd_ari_vec <- vector(mode = "numeric", length = length(files))
perm_ari_vec <- vector(mode = "numeric", length = length(files))

nms <- vector(mode = "character", length = length(files))

options(rlib_message_verbosity = "quiet")
for (i in seq_len(length(files))) {
  f <- files[i]
  fnm <- gsub("_filtered.rds", "", basename(f))
  fnm <- gsub(".rds", "", fnm)

  sce <- readRDS(f)

  if (fnm == "tabula_muris_sub") {
    sce$truth <- sce$cell_ontology_class
  }

  set.seed(1234)
  sce_var <- scran::modelGeneVar(sce)
  sce_top <- scran::getTopHVGs(sce_var, n = 2000, var.threshold = NULL) #1000
  sce <- sce[sce_top, ]
  cnts <- as.matrix(logcounts(sce))

  ca <- cacomp(
    obj = cnts,
    princ_coords = 3,
    dims = 30, #20
    top = nrow(cnts),
    residuals = "pearson",
    clip = TRUE
  )

  cadir <- dirclust_splitmerge(
    caobj = ca,
    k = 10,
    cutoff = NULL,
    method = "random",
    apl_quant = 0.99
  )

  rnd_cutoff <- CAdir:::get_apl_cutoff(
    caobj = ca,
    method = "random",
    group = which(cadir@cell_clusters == "cluster_1"),
    counts = NULL,
    quant = 0.99,
    apl_cutoff_reps = 100,
    axis = "cols"
  )

  perm_cutoff <- CAdir:::get_apl_cutoff(
    caobj = ca,
    method = "random",
    group = which(cadir@cell_clusters == "cluster_1"),
    counts = NULL,
    quant = 0.99,
    apl_cutoff_reps = 10,
    axis = "cols"
  )

  rnd_ang <- CAdir:::rad2deg(rnd_cutoff)
  perm_ang <- CAdir:::rad2deg(perm_cutoff)

  cadir_rnd <- dirclust_splitmerge(
    caobj = ca,
    k = 10,
    cutoff = rnd_ang,
    apl_quant = 0.99
  )

  cadir_perm <- dirclust_splitmerge(
    caobj = ca,
    k = 10,
    cutoff = perm_ang,
    apl_quant = 0.99
  )

  sce$cadir_rnd <- cadir_rnd@cell_clusters
  sce$cadir_perm <- cadir_perm@cell_clusters

  ari_rnd <- aricode::clustComp(sce$cadir_rnd, sce$truth)$ARI
  ari_perm <- aricode::clustComp(sce$cadir_perm, sce$truth)$ARI

  rnd_vec[i] <- rnd_ang
  names(rnd_vec)[i] <- fnm

  perm_vec[i] <- perm_ang
  names(perm_vec)[i] <- fnm
  nms[i] <- fnm

  rnd_ari_vec[i] <- ari_rnd
  names(rnd_ari_vec)[i] <- fnm

  perm_ari_vec[i] <- ari_perm
  names(perm_ari_vec)[i] <- fnm
}

df <- data.frame(
  "name" = nms,
  "rnd" = rnd_vec,
  "perm" = perm_vec,
  "ARI_rnd" = rnd_ari_vec,
  "ARI_perm" = perm_ari_vec
)

options(rlib_message_verbosity = "default")

saveRDS(df, file = file.path(resdir, "ang_df.rds"))
```

# Panel

```{r}

df$name[df$name == "FreytagGold"] <- "Freytag Gold"
df$name[df$name == "PBMC_10X"] <- "PBMC10x"
df$name[df$name == "Tirosh_nonmaglignant"] <- "Tirosh"
df$name[df$name == "ZeiselBrain"] <- "Zeisel"
df$name[df$name == "BaronPancreas"] <- "Baron Pancreas"
df$name[df$name == "dmel_E14-16h"] <- "Dmel Spatial"
df$name[df$name == "tabula_sapiens_tissue"] <- "Tabula Sapiens"
df$name[df$name == "brain_organoids"] <- "Brain Organoids"
df$name[df$name == "tabula_muris_sub"] <- "Tabula Muris"


dfl <- df %>%
  pivot_longer(cols = rnd:perm, names_to = "method", values_to = "angle") %>%
  dplyr::mutate(name = gsub("_", " ", name)) %>%
  dplyr::mutate(ARI = ifelse(method == "rnd", ARI_rnd, ARI_perm))

dfl$name <- factor(
  dfl$name,
  levels = c(
    "Darmanis",
    "Freytag Gold",
    "Tabula Muris",
    "PBMC10x",
    "Tirosh",
    "Zeisel",
    "Baron Pancreas",
    "Dmel Spatial",
    "Tabula Sapiens",
    "Brain Organoids"
  )
)
```

```{r}

ang_comp <- ggplot(dfl, aes(x = name, y = angle, fill = method)) +
  geom_line(aes(group = name), color = "#777777") +
  geom_point(size = 4, shape = 21, color = "#777777") +
  CAdir::scale_fill_mpimg() +
  labs(
    title = "Random vs. permuted θ: Angle",
    x = "dataset",
    y = "angle [degrees]"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(
      size = 10,
      angle = 45,
      hjust = 1,
      color = "black"
    ),
    axis.text.y = element_text(size = 10, color = "black")
  )

ari_comp <- ggplot(dfl, aes(x = name, y = ARI, fill = method)) +
  geom_line(aes(group = name), color = "#777777") +
  geom_point(size = 4, shape = 21, color = "#777777") +
  CAdir::scale_fill_mpimg() +
  labs(title = "Random vs. permuted θ: ARI", x = "dataset", y = "ARI") +
  theme_bw() +
  theme(
    axis.text.x = element_text(
      size = 10,
      angle = 45,
      hjust = 1,
      color = "black"
    ),
    axis.text.y = element_text(size = 10, color = "black")
  )

panel <- ang_comp +
  ari_comp +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 18, face = "bold"))


ggsave(
  plot = panel,
  file = file.path(imgdir, "comparison_angle.pdf"),
  width = 4000,
  height = 2000,
  units = "px"
)

ggsave(
  plot = panel,
  file = file.path(imgdir, "comparison_angle.png"),
  width = 4000,
  height = 2000,
  units = "px"
)
```


# sessionInfo
```{r}
sessionInfo()
```

