---
title: sm_plots
jupyter:
  jupytext:
    formats: 'ipynb,qmd:quarto'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: R 4.4.1
    language: R
    name: ir441
---

# Setup

```{r}
renv::load()
source("./results/utils.R")

suppressPackageStartupMessages({
  devtools::load_all("~/gits/ClemensKohl/CAdir/")
  # library(CAdir)
  library(APL)
  library(SingleCellExperiment)
  library(dplyr)

  library(scater)
  library(scuttle)
  library(scran)

  library(patchwork)
  library(ggtext)
})

options(repr.plot.width = 20, repr.plot.height = 15)

dir <- "./results/"
imgdir <- file.path(dir, "img/review/sm_plots/")
dir.create(imgdir, recursive = TRUE)
```

# Load parameters
```{r}
date <- "20250528_cpu"
evldir <- file.path("./results/benchmarking/results/real/", date, "eval")

options(repr.plot.width = 15, repr.plot.height = 10)
```
```{r}
### Load the results of real data sets
files <- list.files(evldir, "*.rds", full.names = TRUE)

df <- data.frame()
for (file in files) {
  data <- readRDS(file)
  df <- bind_rows(df, data)
}

df$dataset <- gsub("_filtered", "", df$dataset)
```

```{r}
df$dataset[df$dataset == "FreytagGold"] <- "Freytag Gold"
df$dataset[df$dataset == "PBMC_10X"] <- "PBMC10x"
df$dataset[df$dataset == "Tirosh_nonmaglignant"] <- "Tirosh"
df$dataset[df$dataset == "ZeiselBrain"] <- "Zeisel"
df$dataset[df$dataset == "BaronPancreas"] <- "Baron Pancreas"
df$dataset[df$dataset == "dmel_E14-16h"] <- "Dmel Spatial"
df$dataset[df$dataset == "tabula_sapiens_tissue"] <- "Tabula Sapiens"
df$dataset[df$dataset == "brain_organoids"] <- "Brain Organoids"

df <- df %>%
  mutate(algorithm = gsub("CAbiNet_igraph", "CAbiNet", algorithm)) %>%
  mutate(pattern = paste0(algorithm, dataset))
```

```{r}
# Filter out combinations where all runs fail.
test <- df %>%
  group_by(dataset, algorithm) %>%
  mutate(fail.n = sum(is.na(ARI)), scsd.n = n()) %>%
  filter(fail.n == scsd.n | (scsd.n == 0))

## pick 1 algor./dataset combinaton of failed runs
df_na <- test %>%
  group_by(algorithm, dataset) %>%
  arrange(runtime) %>%
  select(-fail.n, -scsd.n) %>%
  top_n(n = 1, wt = runtime)

## run_stat <- table(df$algorithm, df$dataset)
##
## # Find missing runs (no values because crash/error)
## # Find row and column indices of cells equal to 0
## zero_indices <- which(run_stat == 0, arr.ind = TRUE)
##
## # Create a data frame with row names and column names
## zero_df <- data.frame(
##   algorithm = rownames(run_stat)[zero_indices[, 1]],
##   dataset = colnames(run_stat)[zero_indices[, 2]]
## )
##
## df_na <- dplyr::bind_rows(df_na, zero_df)
```

```{r}
# Filter out runs which failed
subdf <- df[!(df$pattern %in% test$pattern), ]
subdf <- subdf[!is.na(subdf$ARI), ]
subdf <- rbind(subdf, df_na) # add a single instance of failed runs & missing runs.

subdf$algorithm <- factor(
  subdf$algorithm,
  levels = c(
    "CAdir",
    "CAdir_auto",
    "kmeans",
    "CAbiNet",
    "RaceID",
    "RaceID_auto",
    "Seurat",
    "Monocle3",
    "SC3",
    "SIMLR",
    "scDeepCluster",
    "scG-cluster"
  )
)

df_g <- subdf %>%
  group_by(algorithm, dataset) %>%
  mutate(
    Mean_ARI = mean(ARI),
    Max_ARI = max(ARI),
    Median_ARI = median(ARI),
    Mean_NMI = mean(NMI),
    Max_NMI = max(NMI)
  )

df_g$dataset <- factor(
  df_g$dataset,
  levels = c(
    "Darmanis",
    "Freytag Gold",
    "PBMC10x",
    "Tirosh",
    "Zeisel",
    "Baron Pancreas",
    "Dmel Spatial",
    "Tabula Sapiens",
    "Brain Organoids"
  )
)
```

```{r}
df_m <- df_g %>%
  group_by(sim, algorithm, dataset) %>%
  mutate(max_NMI = max(NMI, na.rm = TRUE)) %>%
  mutate(max_ARI = max(ARI, na.rm = TRUE)) %>%
  # select(dataset, sim, algorithm, max_NMI, max_ARI) %>%
  filter(ARI == max_ARI) %>%
  distinct(dataset, sim, algorithm, max_NMI, max_ARI, .keep_all = TRUE) %>%
  ungroup()

df_m$max_NMI[is.infinite(df_m$max_NMI)] <- NA
df_m$max_ARI[is.infinite(df_m$max_ARI)] <- NA
```
# Tirosh

## Load data set

```{r}

file <- "./data/real/preprocessed/benchmarking/Tirosh_nonmaglignant_filtered.rds"
tirosh <- readRDS(file)
```


# Run clustering - Tirosh

```{r}
dft <- df_m %>%
  filter(dataset == "Tirosh") %>%
  filter(algorithm == "CAdir_auto") %>%
  select(
    algorithm,
    dataset,
    ARI,
    max_ARI,
    ntop,
    ngenes,
    dims,
    kdir,
    angle,
    qcut,
    apl_quant
  )
```

```{r}
set.seed(2358)
genevars <- scran::modelGeneVar(tirosh, assay.type = "logcounts")
chosen <- scran::getTopHVGs(genevars, n = dft$ntop, var.threshold = NULL)
tirosh <- tirosh[chosen, ]

cnts <- as.matrix(logcounts(tirosh))

t_caobj <- cacomp(cnts, dims = dft$dims, top = nrow(cnts), python = TRUE)

angle <- as.numeric(dft$angle)
if (angle == 0) {
  angle <- NULL
}
t_cadir <- dirclust_splitmerge(
  caobj = t_caobj,
  k = dft$kdir,
  cutoff = angle,
  method = "random",
  apl_quant = dft$apl_quant,
  qcutoff = dft$qcut,
  counts = NULL,
  min_cells = 20,
  reps = 5,
  make_plots = FALSE
)

t_cadir_anno_cm <- annotate_biclusters(
  obj = t_cadir,
  caobj = t_caobj,
  org = "hs",
  universe = rownames(cnts),
  set = "CellMarker",
  method = "gsea",
  cost = "NES"
)

t_cadir_anno_pdb <- annotate_biclusters(
  obj = t_cadir,
  caobj = t_caobj,
  org = "hs",
  universe = rownames(cnts),
  set = "PanglaoDB",
  method = "gsea",
  cost = "NES"
)

t_cadir

tirosh$cadir <- t_cadir@cell_clusters
ari <- aricode::ARI(tirosh$truth, tirosh$cadir)

cat("Tirosh ARI:", ari)
```
## UMAP
```{r}
t_um1 <- plotUMAP(tirosh, colour = "cadir")
t_um2 <- plotUMAP(tirosh, colour = "truth")

# t_um1 + t_um2

ggsave(
  plot = t_um1,
  filename = file.path(imgdir, "cadir_umap_tirosh.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)

ggsave(
  plot = t_um2,
  filename = file.path(imgdir, "truth_umap_tirosh.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)
```

### Tirosh marker genes T cells

```{r}
t_cadir <- rank_genes(cadir = t_cadir, caobj = t_caobj)
cl3 <- t_cadir@gene_ranks$cluster_3
cl4 <- t_cadir@gene_ranks$cluster_4

cl3 <- cl3[cl3$Score >= 0, ]
cl4 <- cl4[cl4$Score >= 0, ]
```

```{r}
pc3 <- plotExpression(
  tirosh[, tirosh$cadir %in% c("cluster_3", "cluster_4")],
  features = cl3$Rowname[1:4],
  x = "cadir",
  colour_by = "cadir"
) +
  guides(colour = "none") +
  scale_color_mpimg()

pc4 <- plotExpression(
  tirosh[, tirosh$cadir %in% c("cluster_3", "cluster_4")],
  features = cl4$Rowname[1:4],
  x = "cadir",
  colour_by = "cadir"
) +
  guides(colour = "none") +
  scale_color_mpimg()

pcd4 <- plotExpression(
  tirosh[, tirosh$cadir %in% c("cluster_3", "cluster_4")],
  features = "CD4",
  x = "cadir",
  colour_by = "cadir"
) +
  guides(colour = "none") +
  scale_color_mpimg()

ggsave(plot = pc3, filename = file.path(imgdir, "tirosh_cluster3.png"))
ggsave(plot = pc4, filename = file.path(imgdir, "tirosh_cluster4.png"))

ggsave(plot = pcd4, filename = file.path(imgdir, "tirosh_CD4.png"))
```

```{r}

layout <- c(
  area(t = 1, b = 4, l = 1, r = 4),
  area(t = 1, b = 4, l = 5, r = 8),
  area(t = 1, b = 2, l = 9, r = 10)
)

t_cell_panel <- pc3 +
  pc4 +
  pcd4 +
  plot_layout(guides = "collect", design = layout) +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.tag = element_text(size = 16, face = "bold"),
    plot.title = element_text(size = 20, hjust = 0.5, face = "bold")
    # text = element_text(size = 14)
  )
# &
#   theme(plot.tag = element_text(size = 18, face = "bold"))

ggsave(
  plot = t_cell_panel,
  filename = file.path(imgdir, "t_cell_panel.png"),
  width = 3000,
  height = 1800,
  units = "px"
)
```




## SM plot
```{r}
pdf(file = NULL)
t_sm <- sm_plot(
  cadir = t_cadir,
  caobj = t_caobj,
  rm_redund = TRUE,
  keep_end = FALSE,
  highlight_cluster = TRUE,
  show_genes = FALSE,
  annotate_clusters = TRUE,
  org = "hs",
  inlet_side = 0.11,
  title_size = 3,
  show_axis = FALSE,
  layout = "tree",
  rotate = FALSE,
  show_apl = FALSE,
  annotate_leafs = FALSE
)
dev.off()

ggsave(
  plot = t_sm,
  filename = file.path(imgdir, "split_merge_tirosh.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)
```

# Brain organoids

## Load data set
```{r}

file <- "./data/real/preprocessed/benchmarking/brain_organoids_filtered.rds"
brain <- readRDS(file)
```

# Run clustering - Brain Organoids

```{r}
dfb <- df_m %>%
  filter(dataset == "Brain Organoids") %>%
  filter(algorithm == "CAdir_auto") %>%
  select(
    algorithm,
    dataset,
    ARI,
    max_ARI,
    ntop,
    ngenes,
    dims,
    kdir,
    angle,
    qcut,
    apl_quant
  )
```

```{r}
set.seed(2358)
genevars <- scran::modelGeneVar(brain, assay.type = "logcounts")
chosen <- scran::getTopHVGs(genevars, n = dfb$ntop, var.threshold = NULL)
brain <- brain[chosen, ]

cnts <- as.matrix(logcounts(brain))

bo_caobj <- cacomp(cnts, dims = dfb$dims, top = nrow(cnts), python = TRUE)

angle <- as.numeric(dfb$angle)
if (angle == 0) {
  angle <- NULL
}
bo_cadir <- dirclust_splitmerge(
  caobj = bo_caobj,
  k = dfb$kdir,
  cutoff = angle,
  method = "random",
  apl_quant = dfb$apl_quant,
  qcutoff = dfb$qcut,
  counts = NULL,
  min_cells = 20,
  reps = 5,
  make_plots = FALSE
)

bo_cadir

brain$cadir <- bo_cadir@cell_clusters
ari <- aricode::ARI(brain$truth, brain$cadir)
cat("Brain Organoids ARI:", ari)
```
## UMAP
```{r}
bo_um1 <- plotUMAP(brain, colour = "cadir")
bo_um2 <- plotUMAP(brain, colour = "truth")
bo_um3 <- plotUMAP(brain, colour = "cell_line")
bo_um4 <- plotUMAP(brain, colour = "protocol")
bo_um5 <- plotUMAP(brain, colour = "sample")

# bo_um1 + bo_um2

ggsave(
  plot = bo_um1,
  filename = file.path(imgdir, "cadir_umap_brain_organoids.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)

ggsave(
  plot = bo_um2,
  filename = file.path(imgdir, "truth_umap_brain_organoids.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)
```

## SM plot
```{r}

pdf(file = NULL)
bo_sm <- sm_plot(
  cadir = bo_cadir,
  caobj = bo_caobj,
  rm_redund = TRUE,
  keep_end = FALSE,
  highlight_cluster = TRUE,
  show_genes = FALSE,
  annotate_clusters = TRUE,
  org = "hs",
  inlet_side = 0.11,
  title_size = 3,
  show_axis = FALSE,
  layout = "tree",
  rotate = FALSE,
  show_apl = FALSE,
  annotate_leafs = TRUE
)
dev.off()

ggsave(
  plot = bo_sm,
  filename = file.path(imgdir, "split_merge_brain_organoids.png"),
  width = 4000,
  height = 6000,
  units = "px"
)
```


```{r}
rm(list = c("brain", "bo_caobj", "bo_cadir", "cnts"))
```


# Tabula Sapiens

## Load data set
```{r}

file <- "./data/real/preprocessed/benchmarking/tabula_sapiens_tissue_filtered.rds"
tabulas <- readRDS(file)
# rownames(tabulas) <- rowData(tabulas)$SYMBOL
```

# Run clustering - Brain Organoids

```{r}
dfts <- df_m %>%
  filter(dataset == "Tabula Sapiens") %>%
  filter(algorithm == "CAdir_auto") %>%
  select(
    algorithm,
    dataset,
    ARI,
    max_ARI,
    ntop,
    ngenes,
    dims,
    kdir,
    angle,
    qcut,
    apl_quant
  )
```

```{r}
set.seed(2358)
genevars <- scran::modelGeneVar(tabulas, assay.type = "logcounts")
chosen <- scran::getTopHVGs(genevars, n = dfts$ntop, var.threshold = NULL)
tabulas <- tabulas[chosen, ]

cnts <- as.matrix(logcounts(tabulas))

ts_caobj <- cacomp(cnts, dims = dfts$dims, top = nrow(cnts), python = TRUE)

angle <- as.numeric(dfts$angle)
if (angle == 0) {
  angle <- NULL
}
ts_cadir <- dirclust_splitmerge(
  caobj = ts_caobj,
  k = dfts$kdir,
  cutoff = angle,
  method = "random",
  apl_quant = dfts$apl_quant,
  qcutoff = dfts$qcut,
  counts = NULL,
  min_cells = 20,
  reps = 5,
  make_plots = FALSE
)

ts_cadir

tabulas$cadir <- ts_cadir@cell_clusters
ari <- aricode::ARI(tabulas$truth, tabulas$cadir)
cat("Tabula Sapiens ARI:", ari)
```

```{r}

# ts_cadir_anno_cm <- annotate_biclusters(
#   obj = ts_cadir,
#   caobj = ts_caobj,
#   org = "hs",
#   universe = rownames(cnts),
#   set = "CellMarker",
#   method = "gsea",
#   cost = "NES"
# )
#
# ts_cadir_anno_pdb <- annotate_biclusters(
#   obj = ts_cadir,
#   caobj = ts_caobj,
#   org = "hs",
#   universe = rownames(cnts),
#   set = "PanglaoDB",
#   method = "gsea",
#   cost = "NES"
# )
```


## UMAP
```{r}
ts_um1 <- plotUMAP(tabulas, colour = "cadir")
ts_um2 <- plotUMAP(tabulas, colour = "truth")

# ts_um1 + ts_um2

ggsave(
  plot = ts_um1,
  filename = file.path(imgdir, "cadir_umap_tabula_sapiens.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)

ggsave(
  plot = ts_um2,
  filename = file.path(imgdir, "truth_umap_tabula_sapiens.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)
```

## SM plot
```{r}

pdf(file = NULL)
ts_sm <- sm_plot(
  cadir = ts_cadir,
  caobj = ts_caobj,
  rm_redund = TRUE,
  keep_end = FALSE,
  highlight_cluster = TRUE,
  show_genes = FALSE,
  annotate_clusters = TRUE,
  org = "hs",
  inlet_side = 0.11,
  title_size = 3,
  show_axis = FALSE,
  layout = "tree",
  rotate = FALSE,
  show_apl = FALSE,
  annotate_leafs = TRUE
)
dev.off()

ggsave(
  plot = ts_sm,
  filename = file.path(imgdir, "split_merge_tabula_sapiens.png"),
  width = 4000,
  height = 6000,
  units = "px"
)
```

# Darmanis

## Load data set
```{r}

file <- "./data/real/preprocessed/benchmarking/Darmanis_filtered.rds"
darmanis <- readRDS(file)
# rownames(darmanis) <- rowData(darmanis)$SYMBOL
```

# Run clustering - Brain Organoids

```{r}
dfts <- df_m %>%
  filter(dataset == "Darmanis") %>%
  filter(algorithm == "CAdir_auto") %>%
  select(
    algorithm,
    dataset,
    ARI,
    max_ARI,
    ntop,
    ngenes,
    dims,
    kdir,
    angle,
    qcut,
    apl_quant
  )
```

```{r}
set.seed(2358)
genevars <- scran::modelGeneVar(darmanis, assay.type = "logcounts")
chosen <- scran::getTopHVGs(genevars, n = dfts$ntop, var.threshold = NULL)
darmanis <- darmanis[chosen, ]

cnts <- as.matrix(logcounts(darmanis))

d_caobj <- cacomp(cnts, dims = dfts$dims, top = nrow(cnts), python = TRUE)

angle <- as.numeric(dfts$angle)
if (angle == 0) {
  angle <- NULL
}
d_cadir <- dirclust_splitmerge(
  caobj = d_caobj,
  k = dfts$kdir,
  cutoff = angle,
  method = "random",
  apl_quant = dfts$apl_quant,
  qcutoff = dfts$qcut,
  counts = NULL,
  min_cells = 20,
  reps = 5,
  make_plots = FALSE
)

d_cadir

darmanis$cadir <- d_cadir@cell_clusters
ari <- aricode::ARI(darmanis$truth, darmanis$cadir)
cat("Darmanis ARI:", ari)
```

```{r}

# ts_cadir_anno_cm <- annotate_biclusters(
#   obj = d_cadir,
#   caobj = d_caobj,
#   org = "hs",
#   universe = rownames(cnts),
#   set = "CellMarker",
#   method = "gsea",
#   cost = "NES"
# )
#
# ts_cadir_anno_pdb <- annotate_biclusters(
#   obj = d_cadir,
#   caobj = d_caobj,
#   org = "hs",
#   universe = rownames(cnts),
#   set = "PanglaoDB",
#   method = "gsea",
#   cost = "NES"
# )
```


## UMAP
```{r}
d_um1 <- plotUMAP(darmanis, colour = "cadir")
d_um2 <- plotUMAP(darmanis, colour = "truth")

# ts_um1 + ts_um2

ggsave(
  plot = d_um1,
  filename = file.path(imgdir, "cadir_umap_darmanis.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)

ggsave(
  plot = d_um2,
  filename = file.path(imgdir, "truth_umap_darmanis.png")
  # width = 6000,
  # height = 4000,
  # units = "px"
)
```


# Panels

## UMAPs
```{r}

# layout <- c(
#   area(t = 1, b = 4, l = 1, r = 4),
#   area(t = 5, b = 8, l = 1, r = 4),
#   area(t = 1, b = 4, l = 5, r = 8),
#   area(t = 5, b = 8, l = 5, r = 8),
#   area(t = 1, b = 4, l = 9, r = 12),
#   area(t = 5, b = 8, l = 9, r = 12)
# )

layout <- c(
  area(t = 1, b = 4, l = 1, r = 4),
  area(t = 1, b = 4, l = 5, r = 8),
  area(t = 5, b = 8, l = 1, r = 4),
  area(t = 5, b = 8, l = 5, r = 8),
  area(t = 9, b = 12, l = 1, r = 4),
  area(t = 9, b = 12, l = 5, r = 8)
)

umap_panel <- (t_um1 + ggtitle("Tirosh - CAdir")) +
  (t_um2 + ggtitle("Tirosh - Annotation")) +
  (bo_um1 + ggtitle("Brain Organoids - CAdir")) +
  (bo_um2 + ggtitle("Brain Organoids - Annotation")) +
  (ts_um1 + ggtitle("Tabula Sapiens - CAdir")) +
  (ts_um2 + ggtitle("Tabula Sapiens - Annotation")) +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.tag = element_text(size = 18, face = "bold"),
    plot.title = element_text(size = 20),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 18)
  )

ggsave(
  plot = umap_panel,
  filename = file.path(imgdir, "difficult_clusterings_umaps.png"),
  width = 8000,
  height = 8000,
  units = "px"
)
```

```{r}
# layout <- c(
#   area(t = 1, b = 4, l = 1, r = 4),
#   area(t = 5, b = 8, l = 1, r = 4),
#   area(t = 1, b = 4, l = 5, r = 8),
#   area(t = 5, b = 8, l = 5, r = 8),
#   area(t = 1, b = 4, l = 9, r = 12),
#   area(t = 5, b = 8, l = 9, r = 12),
#   area(t = 1, b = 4, l = 13, r = 16),
#   area(t = 5, b = 8, l = 13, r = 16)
# )

layout <- c(
  area(t = 1, b = 4, l = 1, r = 4),
  area(t = 5, b = 8, l = 1, r = 4),
  area(t = 1, b = 4, l = 5, r = 8),
  area(t = 5, b = 8, l = 5, r = 8),
  area(t = 9, b = 12, l = 1, r = 4),
  area(t = 13, b = 16, l = 1, r = 4),
  area(t = 9, b = 12, l = 5, r = 8),
  area(t = 13, b = 16, l = 5, r = 8)
)

umap_panel <- (t_um1 + ggtitle("Tirosh - CAdir")) +
  (t_um2 + ggtitle("Tirosh - Annotation")) +
  (bo_um1 + ggtitle("Brain Organoids - CAdir")) +
  (bo_um2 + ggtitle("Brain Organoids - Annotation")) +
  (ts_um1 + ggtitle("Tabula Sapiens - CAdir")) +
  (ts_um2 + ggtitle("Tabula Sapiens - Annotation")) +
  (d_um1 + ggtitle("Darmanis - CAdir")) +
  (d_um2 + ggtitle("Darmanis - Annotation")) +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.tag = element_text(size = 18, face = "bold"),
    plot.title = element_text(size = 20),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 18)
  )

ggsave(
  plot = umap_panel,
  filename = file.path(imgdir, "difficult_clusterings_ALL_umaps.png"),
  width = 8000,
  height = 8000,
  units = "px"
)
```


## Split Merge Plots
```{r}

sm_panel <- wrap_plots(t_sm + ggtitle("Tirosh")) +
  wrap_plots(bo_sm + ggtitle("Brain Organoids")) +
  wrap_plots(ts_sm + ggtitle("Tabula Sapiens")) +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.tag = element_text(size = 24, face = "bold"),
    plot.title = element_text(size = 26, hjust = 0.5, face = "bold"),
    text = element_text(size = 14)
  )
# &
#   theme(plot.tag = element_text(size = 18, face = "bold"))

ggsave(
  plot = sm_panel,
  filename = file.path(imgdir, "difficult_clusterings_split_merge.png"),
  width = 8000,
  height = 4000,
  units = "px"
)
```



# Session Info
```{r}
sessionInfo()
```


